# Generated by Django 4.2.4 on 2023-08-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='recipe_image',
            field=models.ImageField(upload_to='static/recipe_images/'),
        ),
    ]
