# Generated by Django 4.2.4 on 2023-08-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userpost_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
