# Generated by Django 4.2.4 on 2023-10-03 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_saved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together={('user', 'recipe')},
        ),
    ]
